# Generated by Django 5.0.4 on 2024-04-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_exchangesrate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangesrate',
            name='user',
        ),
    ]
